<a href="https://colab.research.google.com/github/kmirojo/Ejercicio-Limpieza-Data/blob/main/Limpieza_de_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Limpieza de datos

### Data Casas

#### Imports y configuración

In [139]:
import pandas as pd
import warnings
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from functools import reduce # Nos deja utilizar una función como argumento de otra función

warnings.filterwarnings("ignore")
pd.set_option("display.max_columns", 200) # Limitación de columnas

In [140]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [141]:
df = pd.read_csv("/content/drive/MyDrive/AI & Data Science/data_sets/house_prices_train.csv")
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,None,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [142]:
df.tail()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,6,5,1999,2000,Gable,CompShg,VinylSd,VinylSd,None,0.0,TA,TA,PConc,Gd,TA,No,Unf,0,Unf,0,953,953,GasA,Ex,Y,SBrkr,953,694,0,1647,0,0,2,1,3,1,TA,7,Typ,1,TA,Attchd,1999.0,RFn,2,460,TA,TA,Y,0,40,0,0,0,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,Norm,1Fam,1Story,6,6,1978,1988,Gable,CompShg,Plywood,Plywood,Stone,119.0,TA,TA,CBlock,Gd,TA,No,ALQ,790,Rec,163,589,1542,GasA,TA,Y,SBrkr,2073,0,0,2073,1,0,2,0,3,1,TA,7,Min1,2,TA,Attchd,1978.0,Unf,2,500,TA,TA,Y,349,0,0,0,0,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,9,1941,2006,Gable,CompShg,CemntBd,CmentBd,None,0.0,Ex,Gd,Stone,TA,Gd,No,GLQ,275,Unf,0,877,1152,GasA,Ex,Y,SBrkr,1188,1152,0,2340,0,0,2,0,4,1,Gd,9,Typ,2,Gd,Attchd,1941.0,RFn,1,252,TA,TA,Y,0,60,0,0,0,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,1Fam,1Story,5,6,1950,1996,Hip,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,CBlock,TA,TA,Mn,GLQ,49,Rec,1029,0,1078,GasA,Gd,Y,FuseA,1078,0,0,1078,1,0,1,0,2,1,Gd,5,Typ,0,NaN,Attchd,1950.0,Unf,1,240,TA,TA,Y,366,0,112,0,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,Norm,1Fam,1Story,5,6,1965,1965,Gable,CompShg,HdBoard,HdBoard,None,0.0,Gd,TA,CBlock,TA,TA,No,BLQ,830,LwQ,290,136,1256,GasA,Gd,Y,SBrkr,1256,0,0,1256,1,0,1,1,3,1,TA,6,Typ,0,NaN,Attchd,1965.0,Fin,1,276,TA,TA,Y,736,68,0,0,0,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [143]:
# Verificación de datos unicos por columna para analizar si son "Discretas" o "Continuas"
print("Unique values length ===")
print("MSSubClass: ", len(pd.unique(df['MSSubClass'])))
print("LotArea: ", len(pd.unique(df['LotArea'])))

for columna in df.columns:
  print(columna, len(pd.unique(df[columna])))

Unique values length ===
MSSubClass:  15
LotArea:  1073
Id 1460
MSSubClass 15
MSZoning 5
LotFrontage 111
LotArea 1073
Street 2
Alley 3
LotShape 4
LandContour 4
Utilities 2
LotConfig 5
LandSlope 3
Neighborhood 25
Condition1 9
Condition2 8
BldgType 5
HouseStyle 8
OverallQual 10
OverallCond 9
YearBuilt 112
YearRemodAdd 61
RoofStyle 6
RoofMatl 8
Exterior1st 15
Exterior2nd 16
MasVnrType 5
MasVnrArea 328
ExterQual 4
ExterCond 5
Foundation 6
BsmtQual 5
BsmtCond 5
BsmtExposure 5
BsmtFinType1 7
BsmtFinSF1 637
BsmtFinType2 7
BsmtFinSF2 144
BsmtUnfSF 780
TotalBsmtSF 721
Heating 6
HeatingQC 5
CentralAir 2
Electrical 6
1stFlrSF 753
2ndFlrSF 417
LowQualFinSF 24
GrLivArea 861
BsmtFullBath 4
BsmtHalfBath 3
FullBath 4
HalfBath 3
BedroomAbvGr 8
KitchenAbvGr 4
KitchenQual 4
TotRmsAbvGrd 12
Functional 7
Fireplaces 4
FireplaceQu 6
GarageType 7
GarageYrBlt 98
GarageFinish 4
GarageCars 5
GarageArea 441
GarageQual 6
GarageCond 6
PavedDrive 3
WoodDeckSF 274
OpenPorchSF 202
EnclosedPorch 120
3SsnPorch 20
ScreenPorch 76
PoolArea 8
PoolQC 4
Fence 5
MiscFeature 5
MiscVal 21
MoSold 12
YrSold 5
SaleType 9
SaleCondition 6
SalePrice 663

In [144]:
# Renombrando columnas con prefijo para datos "Discretas", "Continuas" y "Target"
def rename_cols(df, columnas, prefijo):
  nuevos = [prefijo + col for col in columnas]
  df = df.rename(columns=dict(zip(columnas, nuevos)))
  return df

v_feats=["MSSubClass","MSZoning","Street","Alley","LotShape","LandContour","Utilities","LotConfig","LandSlope",
         "Neighborhood","Condition1","Condition2","BldgType","HouseStyle","OverallQual","OverallCond",
        "YearBuilt","YearRemodAdd","RoofStyle","RoofMatl","Exterior1st","Exterior2nd","MasVnrType","ExterQual",
        "ExterCond","Foundation","BsmtQual","BsmtCond","BsmtExposure","BsmtFinType1","BsmtFinType2",
        "Heating","HeatingQC","CentralAir","Electrical","LowQualFinSF","BsmtHalfBath","FullBath","KitchenAbvGr","KitchenQual","TotRmsAbvGrd","Functional","Fireplaces","FireplaceQu",
        "GarageType","GarageYrBlt","GarageFinish","GarageQual","GarageCond","PavedDrive","PoolQC","Fence",
        "MiscFeature","MoSold","YrSold","SaleType","SaleCondition"]
c_feats=["LotFrontage","LotArea","MasVnrArea","BsmtFinSF1","BsmtFinSF2","BsmtUnfSF","TotalBsmtSF","1stFlrSF",
        "2ndFlrSF","GrLivArea","GarageArea","WoodDeckSF","OpenPorchSF","EnclosedPorch","3SsnPorch","ScreenPorch",
        "PoolArea","MiscVal","BedroomAbvGr","HalfBath","GarageCars","BsmtFullBath"]
tgt=["SalePrice"]

df = rename_cols(df, v_feats, "v_")
df = rename_cols(df, c_feats, "c_")
df = rename_cols(df, tgt, "tgt_")

In [145]:
df.head()

,Id,v_MSSubClass,v_MSZoning,c_LotFrontage,c_LotArea,v_Street,v_Alley,v_LotShape,v_LandContour,v_Utilities,v_LotConfig,v_LandSlope,v_Neighborhood,v_Condition1,v_Condition2,v_BldgType,v_HouseStyle,v_OverallQual,v_OverallCond,v_YearBuilt,v_YearRemodAdd,v_RoofStyle,v_RoofMatl,v_Exterior1st,v_Exterior2nd,v_MasVnrType,c_MasVnrArea,v_ExterQual,v_ExterCond,v_Foundation,v_BsmtQual,v_BsmtCond,v_BsmtExposure,v_BsmtFinType1,c_BsmtFinSF1,v_BsmtFinType2,c_BsmtFinSF2,c_BsmtUnfSF,c_TotalBsmtSF,v_Heating,v_HeatingQC,v_CentralAir,v_Electrical,c_1stFlrSF,c_2ndFlrSF,v_LowQualFinSF,c_GrLivArea,c_BsmtFullBath,v_BsmtHalfBath,v_FullBath,c_HalfBath,c_BedroomAbvGr,v_KitchenAbvGr,v_KitchenQual,v_TotRmsAbvGrd,v_Functional,v_Fireplaces,v_FireplaceQu,v_GarageType,v_GarageYrBlt,v_GarageFinish,c_GarageCars,c_GarageArea,v_GarageQual,v_GarageCond,v_PavedDrive,c_WoodDeckSF,c_OpenPorchSF,c_EnclosedPorch,c_3SsnPorch,c_ScreenPorch,c_PoolArea,v_PoolQC,v_Fence,v_MiscFeature,c_MiscVal,v_MoSold,v_YrSold,v_SaleType,v_SaleCondition,tgt_SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,None,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [146]:
df.drop(columns=['Id'], inplace=True)
df.head()

,v_MSSubClass,v_MSZoning,c_LotFrontage,c_LotArea,v_Street,v_Alley,v_LotShape,v_LandContour,v_Utilities,v_LotConfig,v_LandSlope,v_Neighborhood,v_Condition1,v_Condition2,v_BldgType,v_HouseStyle,v_OverallQual,v_OverallCond,v_YearBuilt,v_YearRemodAdd,v_RoofStyle,v_RoofMatl,v_Exterior1st,v_Exterior2nd,v_MasVnrType,c_MasVnrArea,v_ExterQual,v_ExterCond,v_Foundation,v_BsmtQual,v_BsmtCond,v_BsmtExposure,v_BsmtFinType1,c_BsmtFinSF1,v_BsmtFinType2,c_BsmtFinSF2,c_BsmtUnfSF,c_TotalBsmtSF,v_Heating,v_HeatingQC,v_CentralAir,v_Electrical,c_1stFlrSF,c_2ndFlrSF,v_LowQualFinSF,c_GrLivArea,c_BsmtFullBath,v_BsmtHalfBath,v_FullBath,c_HalfBath,c_BedroomAbvGr,v_KitchenAbvGr,v_KitchenQual,v_TotRmsAbvGrd,v_Functional,v_Fireplaces,v_FireplaceQu,v_GarageType,v_GarageYrBlt,v_GarageFinish,c_GarageCars,c_GarageArea,v_GarageQual,v_GarageCond,v_PavedDrive,c_WoodDeckSF,c_OpenPorchSF,c_EnclosedPorch,c_3SsnPorch,c_ScreenPorch,c_PoolArea,v_PoolQC,v_Fence,v_MiscFeature,c_MiscVal,v_MoSold,v_YrSold,v_SaleType,v_SaleCondition,tgt_SalePrice
0,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,None,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [147]:
# Información sobre las columnas continuas
df.filter(like="c_").info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   c_LotFrontage    1201 non-null   float64
 1   c_LotArea        1460 non-null   int64
 2   c_MasVnrArea     1452 non-null   float64
 3   c_BsmtFinSF1     1460 non-null   int64
 4   c_BsmtFinSF2     1460 non-null   int64
 5   c_BsmtUnfSF      1460 non-null   int64
 6   c_TotalBsmtSF    1460 non-null   int64
 7   c_1stFlrSF       1460 non-null   int64
 8   c_2ndFlrSF       1460 non-null   int64
 9   c_GrLivArea      1460 non-null   int64
 10  c_BsmtFullBath   1460 non-null   int64
 11  c_HalfBath       1460 non-null   int64
 12  c_BedroomAbvGr   1460 non-null   int64
 13  c_GarageCars     1460 non-null   int64
 14  c_GarageArea     1460 non-null   int64
 15  c_WoodDeckSF     1460 non-null   int64
 16  c_OpenPorchSF    1460 non-null   int64
 17  c_EnclosedPorch  1460 non-null   int64
 18  c_3SsnPorch      1460 non-null   int64
 19  c_ScreenPorch    1460 non-null   int64
 20  c_PoolArea       1460 non-null   int64
 21  c_MiscVal        1460 non-null   int64
dtypes: float64(2), int64(20)
memory usage: 251.1 KB

#### Analisis de completitud

In [148]:
completitud = pd.DataFrame(df.isnull().sum())
completitud.reset_index(inplace=True) # Reorganización de los indices que trae el df de completitud
completitud = completitud.rename(columns={"index": "columna", 0: "total"}) # Renombrando las columnas de completitud para mayor claridad
completitud["completitud"] = (1 - completitud["total"] / df.shape[0]) * 100 # Calcular porcentaje de completitud por cada columna
completitud = completitud.sort_values(by="completitud", ascending=True) # Reorganiza los datos con todo e indices
completitud.reset_index(drop=True, inplace=True) # Cómo los indices tmb están reorganizados, se reinicia su posición

completitud

          columna  total  completitud
0        v_PoolQC   1453     0.479452
1   v_MiscFeature   1406     3.698630
2         v_Alley   1369     6.232877
3         v_Fence   1179    19.246575
4   v_FireplaceQu    690    52.739726
..            ...    ...          ...
75  v_Exterior2nd      0   100.000000
76  v_Exterior1st      0   100.000000
77     v_RoofMatl      0   100.000000
78   c_BsmtFinSF1      0   100.000000
79  tgt_SalePrice      0   100.000000

[80 rows x 3 columns]

In [149]:
# Completitud arriba del 80%
# (No es recomendable hacer completado de datos a columnas con menos del 80% de completitud)

# Listar datasets con menos del 80% de completitud
para_eliminar = list(completitud[completitud['completitud'] < 80]['columna'].values)
para_eliminar

['v_PoolQC', 'v_MiscFeature', 'v_Alley', 'v_Fence', 'v_FireplaceQu']

In [150]:
# Se eliminan los datasets con completitud inferior al 80%
df = df.drop(columns=para_eliminar)
df.shape

(1460, 75)

In [151]:
# Revisar de nuevo el porcentaje de completitud

completitud = pd.DataFrame(df.isnull().sum())
completitud.reset_index(inplace=True) # Reorganización de los indices que trae el df de completitud
completitud = completitud.rename(columns={"index": "columna", 0: "total"}) # Renombrando las columnas de completitud para mayor claridad
completitud["completitud"] = (1 - completitud["total"] / df.shape[0]) * 100 # Calcular porcentaje de completitud por cada columna
completitud = completitud.sort_values(by="completitud", ascending=True) # Reorganiza los datos con todo e indices
completitud.reset_index(drop=True, inplace=True) # Cómo los indices tmb están reorganizados, se reinicia su posición

# Listar datasets con menos del 80% de completitud
para_eliminar = list(completitud[completitud['completitud'] < 80]['columna'].values)
para_eliminar # En este punto, debería retornar una lista vacia

[]

#### Imputación - Completar datos faltantes

In [152]:
from sklearn.impute import SimpleImputer

In [153]:
# seleccionar columnas que deben ser imputadas (con porcentaje de completitud inferior a 100)
imputacion = list(completitud[completitud['completitud'] != 100]['columna'].values)
imputacion

['c_LotFrontage',
 'v_GarageType',
 'v_GarageYrBlt',
 'v_GarageFinish',
 'v_GarageQual',
 'v_GarageCond',
 'v_BsmtFinType2',
 'v_BsmtExposure',
 'v_BsmtCond',
 'v_BsmtQual',
 'v_BsmtFinType1',
 'v_MasVnrType',
 'c_MasVnrArea',
 'v_Electrical']

In [154]:
# Se puede decir que "para_imputar" es un "modelo" y "para_imputar.fit" es entrenarlo ¿?
para_imputar = SimpleImputer(missing_values=np.nan, strategy='most_frequent') # Completamos por moda
para_imputar.fit(df[imputacion])

SimpleImputer(strategy='most_frequent')

In [155]:
# Pasos básicos para implementar un modelo IA:

# 1. Definir el Modelo
# 2. Entrenar el modelo con los datos
# 3. Implementar o predecir

df[imputacion] = para_imputar.transform(df[imputacion]) # Aplicar nuestro modelo de IA (SimpleImputer) a nuestro dataset

In [156]:
# Verificar de nuevo la completitud

completitud = pd.DataFrame(df.isnull().sum())
completitud.reset_index(inplace=True) # Reorganización de los indices que trae el df de completitud
completitud = completitud.rename(columns={"index": "columna", 0: "total"}) # Renombrando las columnas de completitud para mayor claridad
completitud["completitud"] = (1 - completitud["total"] / df.shape[0]) * 100 # Calcular porcentaje de completitud por cada columna
completitud = completitud.sort_values(by="completitud", ascending=True) # Reorganiza los datos con todo e indices
completitud.reset_index(drop=True, inplace=True) # Cómo los indices tmb están reorganizados, se reinicia su posición

completitud # A este punto el porcentaje de completitud debe ser de 100%

           columna  total  completitud
0     v_MSSubClass      0        100.0
1     v_Functional      0        100.0
2   v_TotRmsAbvGrd      0        100.0
3    v_KitchenQual      0        100.0
4   v_KitchenAbvGr      0        100.0
..             ...    ...          ...
70   v_Exterior2nd      0        100.0
71   v_Exterior1st      0        100.0
72      v_RoofMatl      0        100.0
73  v_YearRemodAdd      0        100.0
74   tgt_SalePrice      0        100.0

[75 rows x 3 columns]

In [157]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 75 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   v_MSSubClass     1460 non-null   int64
 1   v_MSZoning       1460 non-null   object
 2   c_LotFrontage    1460 non-null   object
 3   c_LotArea        1460 non-null   int64
 4   v_Street         1460 non-null   object
 5   v_LotShape       1460 non-null   object
 6   v_LandContour    1460 non-null   object
 7   v_Utilities      1460 non-null   object
 8   v_LotConfig      1460 non-null   object
 9   v_LandSlope      1460 non-null   object
 10  v_Neighborhood   1460 non-null   object
 11  v_Condition1     1460 non-null   object
 12  v_Condition2     1460 non-null   object
 13  v_BldgType       1460 non-null   object
 14  v_HouseStyle     1460 non-null   object
 15  v_OverallQual    1460 non-null   int64
 16  v_OverallCond    1460 non-null   int64
 17  v_YearBuilt      1460 non-null   int64
 18  v_YearRemodAdd   1460 non-null   int64
 19  v_RoofStyle      1460 non-null   object
 20  v_RoofMatl       1460 non-null   object
 21  v_Exterior1st    1460 non-null   object
 22  v_Exterior2nd    1460 non-null   object
 23  v_MasVnrType     1460 non-null   object
 24  c_MasVnrArea     1460 non-null   object
 25  v_ExterQual      1460 non-null   object
 26  v_ExterCond      1460 non-null   object
 27  v_Foundation     1460 non-null   object
 28  v_BsmtQual       1460 non-null   object
 29  v_BsmtCond       1460 non-null   object
 30  v_BsmtExposure   1460 non-null   object
 31  v_BsmtFinType1   1460 non-null   object
 32  c_BsmtFinSF1     1460 non-null   int64
 33  v_BsmtFinType2   1460 non-null   object
 34  c_BsmtFinSF2     1460 non-null   int64
 35  c_BsmtUnfSF      1460 non-null   int64
 36  c_TotalBsmtSF    1460 non-null   int64
 37  v_Heating        1460 non-null   object
 38  v_HeatingQC      1460 non-null   object
 39  v_CentralAir     1460 non-null   object
 40  v_Electrical     1460 non-null   object
 41  c_1stFlrSF       1460 non-null   int64
 42  c_2ndFlrSF       1460 non-null   int64
 43  v_LowQualFinSF   1460 non-null   int64
 44  c_GrLivArea      1460 non-null   int64
 45  c_BsmtFullBath   1460 non-null   int64
 46  v_BsmtHalfBath   1460 non-null   int64
 47  v_FullBath       1460 non-null   int64
 48  c_HalfBath       1460 non-null   int64
 49  c_BedroomAbvGr   1460 non-null   int64
 50  v_KitchenAbvGr   1460 non-null   int64
 51  v_KitchenQual    1460 non-null   object
 52  v_TotRmsAbvGrd   1460 non-null   int64
 53  v_Functional     1460 non-null   object
 54  v_Fireplaces     1460 non-null   int64
 55  v_GarageType     1460 non-null   object
 56  v_GarageYrBlt    1460 non-null   object
 57  v_GarageFinish   1460 non-null   object
 58  c_GarageCars     1460 non-null   int64
 59  c_GarageArea     1460 non-null   int64
 60  v_GarageQual     1460 non-null   object
 61  v_GarageCond     1460 non-null   object
 62  v_PavedDrive     1460 non-null   object
 63  c_WoodDeckSF     1460 non-null   int64
 64  c_OpenPorchSF    1460 non-null   int64
 65  c_EnclosedPorch  1460 non-null   int64
 66  c_3SsnPorch      1460 non-null   int64
 67  c_ScreenPorch    1460 non-null   int64
 68  c_PoolArea       1460 non-null   int64
 69  c_MiscVal        1460 non-null   int64
 70  v_MoSold         1460 non-null   int64
 71  v_YrSold         1460 non-null   int64
 72  v_SaleType       1460 non-null   object
 73  v_SaleCondition  1460 non-null   object
 74  tgt_SalePrice    1460 non-null   int64
dtypes: int64(34), object(41)
memory usage: 855.6+ KB

In [158]:
df['c_LotFrontage'] = df['c_LotFrontage'].astype('int64') # Convertir un tipo de dato de la columna a otro tipo de dato

In [159]:
df['c_MasVnrArea'] = df['c_MasVnrArea'].astype('int64') # Convertir un tipo de dato de la columna a otro tipo de dato

In [160]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 75 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   v_MSSubClass     1460 non-null   int64
 1   v_MSZoning       1460 non-null   object
 2   c_LotFrontage    1460 non-null   int64
 3   c_LotArea        1460 non-null   int64
 4   v_Street         1460 non-null   object
 5   v_LotShape       1460 non-null   object
 6   v_LandContour    1460 non-null   object
 7   v_Utilities      1460 non-null   object
 8   v_LotConfig      1460 non-null   object
 9   v_LandSlope      1460 non-null   object
 10  v_Neighborhood   1460 non-null   object
 11  v_Condition1     1460 non-null   object
 12  v_Condition2     1460 non-null   object
 13  v_BldgType       1460 non-null   object
 14  v_HouseStyle     1460 non-null   object
 15  v_OverallQual    1460 non-null   int64
 16  v_OverallCond    1460 non-null   int64
 17  v_YearBuilt      1460 non-null   int64
 18  v_YearRemodAdd   1460 non-null   int64
 19  v_RoofStyle      1460 non-null   object
 20  v_RoofMatl       1460 non-null   object
 21  v_Exterior1st    1460 non-null   object
 22  v_Exterior2nd    1460 non-null   object
 23  v_MasVnrType     1460 non-null   object
 24  c_MasVnrArea     1460 non-null   int64
 25  v_ExterQual      1460 non-null   object
 26  v_ExterCond      1460 non-null   object
 27  v_Foundation     1460 non-null   object
 28  v_BsmtQual       1460 non-null   object
 29  v_BsmtCond       1460 non-null   object
 30  v_BsmtExposure   1460 non-null   object
 31  v_BsmtFinType1   1460 non-null   object
 32  c_BsmtFinSF1     1460 non-null   int64
 33  v_BsmtFinType2   1460 non-null   object
 34  c_BsmtFinSF2     1460 non-null   int64
 35  c_BsmtUnfSF      1460 non-null   int64
 36  c_TotalBsmtSF    1460 non-null   int64
 37  v_Heating        1460 non-null   object
 38  v_HeatingQC      1460 non-null   object
 39  v_CentralAir     1460 non-null   object
 40  v_Electrical     1460 non-null   object
 41  c_1stFlrSF       1460 non-null   int64
 42  c_2ndFlrSF       1460 non-null   int64
 43  v_LowQualFinSF   1460 non-null   int64
 44  c_GrLivArea      1460 non-null   int64
 45  c_BsmtFullBath   1460 non-null   int64
 46  v_BsmtHalfBath   1460 non-null   int64
 47  v_FullBath       1460 non-null   int64
 48  c_HalfBath       1460 non-null   int64
 49  c_BedroomAbvGr   1460 non-null   int64
 50  v_KitchenAbvGr   1460 non-null   int64
 51  v_KitchenQual    1460 non-null   object
 52  v_TotRmsAbvGrd   1460 non-null   int64
 53  v_Functional     1460 non-null   object
 54  v_Fireplaces     1460 non-null   int64
 55  v_GarageType     1460 non-null   object
 56  v_GarageYrBlt    1460 non-null   object
 57  v_GarageFinish   1460 non-null   object
 58  c_GarageCars     1460 non-null   int64
 59  c_GarageArea     1460 non-null   int64
 60  v_GarageQual     1460 non-null   object
 61  v_GarageCond     1460 non-null   object
 62  v_PavedDrive     1460 non-null   object
 63  c_WoodDeckSF     1460 non-null   int64
 64  c_OpenPorchSF    1460 non-null   int64
 65  c_EnclosedPorch  1460 non-null   int64
 66  c_3SsnPorch      1460 non-null   int64
 67  c_ScreenPorch    1460 non-null   int64
 68  c_PoolArea       1460 non-null   int64
 69  c_MiscVal        1460 non-null   int64
 70  v_MoSold         1460 non-null   int64
 71  v_YrSold         1460 non-null   int64
 72  v_SaleType       1460 non-null   object
 73  v_SaleCondition  1460 non-null   object
 74  tgt_SalePrice    1460 non-null   int64
dtypes: int64(36), object(39)
memory usage: 855.6+ KB

#### Identificar y eliminar valores Atípicos (Muy Grandes o muy pequeños)

In [161]:
df['c_LotFrontage'].describe()

count    1460.000000
mean       68.267123
std        22.356355
min        21.000000
25%        60.000000
50%        63.000000
75%        79.000000
max       313.000000
Name: c_LotFrontage, dtype: float64

In [162]:
# IQR => Metodo de detección de datos atípicos
# Cuartiles => (25%, 50%, 75%)
columna = 'c_LotFrontage'
q1 = df[columna].quantile(.25)
q3 = df[columna].quantile(.75)

# Restamos el cuartil 1 al cuartil 3 - cuartil3 menos cuartil1
iqr = q3 - q1

print("IQR:", iqr)

# 1.5 => escala de sensibilidad
escala_sensibilidad = 1.5

# Limite inferior
limite_inferior = q1 - escala_sensibilidad * iqr

# Limite superior
limite_superior = q3 + escala_sensibilidad * iqr

print("Limite Superior:", limite_superior)
print("Limite Inferior:", limite_inferior)

IQR: 19.0
Limite Superior: 107.5
Limite Inferior: 31.5

In [163]:
# df.shape[0] => Cantidad de datos
num_iqr = df[(df[columna] <= limite_inferior) | (df[columna] >= limite_superior)][columna].shape[0]
num_iqr

106

In [164]:
# Porcentaje de datos atípicos
# df.shape[0] => Cantidad de datos
(num_iqr / df.shape[0]) * 100

7.260273972602739

In [167]:
print('Total registros (antes de limpieza):',df.shape[0])

Total registros (antes de limpieza): 1460

In [168]:
def atipicos(df, columnas) :
  resultados = pd.DataFrame()
  total = []
  total_per = []
  total_z = []
  indices = []
  for col in columnas :
    q1 = df[col].quantile(.25)
    q3 = df[col].quantile(.75)
    iqr = q3 - q1    
    inf = q1 - 1.5 * (iqr)
    sup = q3 + 1.5 * (iqr)
    # Outliers por IQR    
    num_outliers = df[ (df[col] < inf)  | (df[col] > sup) ].shape[0]
    total.append(num_outliers)
    indices_iqr = list(df[ (df[col] < inf)  | (df[col] > sup) ].index)
    # Determinar percentiles    
    INF_pe = np.percentile(df[col].dropna(), 5)
    SUP_pe = np.percentile(df[col].dropna(), 95)
    num_outliers_per = df[ (df[col] < INF_pe)  | (df[col] > SUP_pe) ].shape[0]
    total_per.append(num_outliers_per)
    indices_per = list(df[ (df[col] < INF_pe)  | (df[col] > SUP_pe)].index)
    # Obtenemos todos los percentiles y el máximo    
    percentil_100 = [x / 100 for x in range(100)]
    distribucion = df[col].describe(percentil_100).iloc[4:]
    # Cambio promedio entre nuestros percentiles    
    cambios_percentil = df[col].describe(percentil_100).iloc[4:].diff()
    cambio_promedio = df[col].describe(percentil_100).iloc[4:].diff().mean()
    # Para demostrar si el máximo es valor atipico    
    if cambios_percentil["max"] > cambio_promedio :
      banda_superior = distribucion["max"] - cambio_promedio      
      if banda_superior < distribucion["99%"] :
        banda_superior = distribucion["99%"]
    else :
      banda_superior = distribucion["max"]
    # Para demostrar si el minimo es valor atipico    
    if cambios_percentil["1%"] > cambio_promedio :
      banda_inferior = distribucion["0%"] + cambio_promedio      
      if banda_inferior > distribucion["1%"] :
        banda_inferior = distribucion["1%"]
    else:
      banda_inferior = distribucion["0%"]
    num_total_z = df[ (df[col] < banda_inferior)  | (df[col] > banda_superior)].shape[0]
    total_z.append(num_total_z)
    indices_z = list(df[ (df[col] < banda_inferior)  | (df[col] > banda_superior)].index)
    indices.append(auxiliar_atipicos(indices_iqr, indices_per, indices_z))
  # END FOR  
  # Ya salimos del FOR  
  resultados["columna"] = columnas  
  resultados["outliers IQR"] = total  
  resultados["outliers Percentil"] = total_per  
  resultados["outliers cambio promedio"] = total_z  
  resultados["outliers IQR %"] = round( (resultados["outliers IQR"] / df.shape[0])*100 , 2)
  resultados["outliers Percentil %"] = round( (resultados["outliers Percentil"] / df.shape[0])*100 , 2)
  resultados["outliers cambio promedio %"] = round( (resultados["outliers cambio promedio"] / df.shape[0])*100 , 2)
  resultados["indices"] = indices  
  resultados["outliers total"] = resultados["indices"].map(lambda x:len(x))
  resultados["% outliers total"] = round((resultados["outliers total"] / df.shape[0]) * 100, 2)
  return resultados 

def auxiliar_atipicos(lista_iqr, lista_per, lista_z) :
  lista_iqr = set(lista_iqr)
  lista_per = set(lista_per)
  lista_z = set(lista_z)
  lista_iqr2 = lista_iqr.intersection(lista_per)
  lista_per2 = lista_per.intersection(lista_z)
  lista_z2 = lista_iqr.intersection(lista_z)
  indices_atipicos = list( set( list(lista_iqr2) + list(lista_per2) + list(lista_z2)) )
  return indices_atipicos

In [169]:
outliers = atipicos(df, list(df.filter(like='c_')))
outliers

,columna,outliers IQR,outliers Percentil,outliers cambio promedio,outliers IQR %,outliers Percentil %,outliers cambio promedio %,indices,outliers total,% outliers total
0,c_LotFrontage,106,145,2,7.26,9.93,0.14,"[1029, 523, 1038, 1039, 25, 35, 36, 1061, 41, ...",106,7.26
1,c_LotArea,69,146,1,4.73,10.00,0.07,"[384, 769, 1409, 260, 1287, 523, 271, 1039, 52...",69,4.73
2,c_MasVnrArea,98,70,1,6.71,4.79,0.07,"[640, 769, 898, 517, 1287, 1289, 1417, 523, 52...",70,4.79
3,c_BsmtFinSF1,7,71,1,0.48,4.86,0.07,"[898, 70, 523, 178, 1298, 53, 1182]",7,0.48
4,c_BsmtFinSF2,167,73,1,11.44,5.00,0.07,"[1024, 1025, 1152, 260, 263, 649, 1418, 271, 1...",73,5.00
5,c_BsmtUnfSF,29,72,1,1.99,4.93,0.07,"[768, 774, 137, 1166, 22, 278, 1046, 798, 928,...",29,1.99
6,c_TotalBsmtSF,61,145,1,4.18,9.93,0.07,"[897, 898, 259, 1412, 646, 392, 520, 778, 523,...",61,4.18
7,c_1stFlrSF,20,146,3,1.37,10.00,0.21,"[1024, 898, 523, 529, 1298, 1044, 533, 1182, 1...",22,1.51
8,c_2ndFlrSF,2,73,1,0.14,5.00,0.07,"[691, 1182]",2,0.14
9,c_GrLivArea,31,141,2,2.12,9.66,0.14,"[1024, 769, 1031, 523, 1169, 1298, 1173, 1046,...",32,2.19
10,c_BsmtFullBath,1,16,1,0.07,1.10,0.07,[738],1,0.07
11,c_HalfBath,0,12,12,0.00,0.82,0.82,"[1154, 1283, 1350, 298, 1163, 1450, 1230, 624,...",12,0.82
12,c_BedroomAbvGr,35,85,7,2.40,5.82,0.48,"[897, 386, 1030, 1031, 1032, 137, 1163, 910, 1...",35,2.40
13,c_GarageCars,5,5,5,0.34,0.34,0.34,"[420, 1350, 1190, 747, 1340]",5,0.34
14,c_GarageArea,21,73,1,1.44,5.00,0.07,"[1417, 270, 1298, 664, 408, 1184, 803, 1061, 1...",21,1.44
15,c_WoodDeckSF,32,71,1,2.19,4.86,0.07,"[769, 1423, 1044, 661, 538, 1312, 1313, 674, 1...",32,2.19
16,c_OpenPorchSF,77,73,1,5.27,5.00,0.07,"[384, 641, 645, 7, 391, 775, 1287, 523, 1164, ...",73,5.00
17,c_EnclosedPorch,208,73,1,14.25,5.00,0.07,"[1152, 3, 260, 1030, 7, 8, 520, 648, 1419, 653...",73,5.00
18,c_3SsnPorch,24,24,1,1.64,1.64,0.07,"[129, 258, 1156, 5, 1161, 280, 922, 1181, 1437...",24,1.64
19,c_ScreenPorch,116,72,1,7.95,4.93,0.07,"[1408, 769, 1154, 1155, 1282, 1414, 647, 907, ...",72,4.93
20,c_PoolArea,7,7,1,0.48,0.48,0.07,"[197, 810, 1386, 1423, 1298, 1170, 1182]",7,0.48
21,c_MiscVal,52,52,1,3.56,3.56,0.07,"[5, 7, 392, 766, 16, 17, 786, 912, 1171, 794, ...",52,3.56

In [171]:
indices = list(outliers['indices'].values)
indices = list(set(reduce(lambda x,y: x + y, indices)))
print('Registros atípicos:', len(indices))

Registros atípicos: 582

In [172]:
len(indices) / df.shape[0]

0.39863013698630134

In [173]:
# ~ Operador NOT Bit a bit. Realizar una operación bit a bit Not
df = df[~df.index.isin(indices)].reset_index(drop=True)
df.head()

,v_MSSubClass,v_MSZoning,c_LotFrontage,c_LotArea,v_Street,v_LotShape,v_LandContour,v_Utilities,v_LotConfig,v_LandSlope,v_Neighborhood,v_Condition1,v_Condition2,v_BldgType,v_HouseStyle,v_OverallQual,v_OverallCond,v_YearBuilt,v_YearRemodAdd,v_RoofStyle,v_RoofMatl,v_Exterior1st,v_Exterior2nd,v_MasVnrType,c_MasVnrArea,v_ExterQual,v_ExterCond,v_Foundation,v_BsmtQual,v_BsmtCond,v_BsmtExposure,v_BsmtFinType1,c_BsmtFinSF1,v_BsmtFinType2,c_BsmtFinSF2,c_BsmtUnfSF,c_TotalBsmtSF,v_Heating,v_HeatingQC,v_CentralAir,v_Electrical,c_1stFlrSF,c_2ndFlrSF,v_LowQualFinSF,c_GrLivArea,c_BsmtFullBath,v_BsmtHalfBath,v_FullBath,c_HalfBath,c_BedroomAbvGr,v_KitchenAbvGr,v_KitchenQual,v_TotRmsAbvGrd,v_Functional,v_Fireplaces,v_GarageType,v_GarageYrBlt,v_GarageFinish,c_GarageCars,c_GarageArea,v_GarageQual,v_GarageCond,v_PavedDrive,c_WoodDeckSF,c_OpenPorchSF,c_EnclosedPorch,c_3SsnPorch,c_ScreenPorch,c_PoolArea,c_MiscVal,v_MoSold,v_YrSold,v_SaleType,v_SaleCondition,tgt_SalePrice
0,60,RL,65,8450,Pave,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,0,2,2008,WD,Normal,208500
1,20,RL,80,9600,Pave,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,None,0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,0,5,2007,WD,Normal,181500
2,60,RL,68,11250,Pave,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,0,9,2008,WD,Normal,223500
3,60,RL,84,14260,Pave,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,0,12,2008,WD,Normal,250000
4,20,RL,75,10084,Pave,Reg,Lvl,AllPub,Inside,Gtl,Somerst,Norm,Norm,1Fam,1Story,8,5,2004,2005,Gable,CompShg,VinylSd,VinylSd,Stone,186,Gd,TA,PConc,Ex,TA,Av,GLQ,1369,Unf,0,317,1686,GasA,Ex,Y,SBrkr,1694,0,0,1694,1,0,2,0,3,1,Gd,7,Typ,1,Attchd,2004.0,RFn,2,636,TA,TA,Y,255,57,0,0,0,0,0,8,2007,WD,Normal,307000

In [174]:
print('Total registros (Post limpieza):',df.shape[0])

Total registros (Post limpieza): 878